#!/bin/sh -e

mkdir build
cd build

echo "rootsbindir=/usr/bin" >> configparms
echo "sbindir=/usr/bin" >> configparms
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --disable-nscd                     \
      libc_cv_slibdir=/usr/lib           \
      --enable-kernel=5.4

make
make DESTDIR=$1 install

sed '/RTLDLIST=/s@/usr@@g' -i $1/usr/bin/ldd

if [ "$MULTILIB" = "1" ]; then
#32bit
make clean
find .. -name "*.a" -delete
CC="$LFS_TGT-gcc -m32" \
CXX="$LFS_TGT-g++ -m32" \
../configure                             \
      --prefix=/usr                      \
      --host=$LFS_TGT32                  \
      --build=$(../scripts/config.guess) \
      --disable-nscd                     \
      --with-headers=$LFS/usr/include    \
      --libdir=/usr/lib32                \
      --libexecdir=/usr/lib32            \
      libc_cv_slibdir=/usr/lib32         \
      --enable-kernel=5.4

make
make DESTDIR=$PWD/DESTDIR install
cp -a DESTDIR/usr/lib32 $1/usr/
install -vm644 DESTDIR/usr/include/gnu/{lib-names,stubs}-32.h \
               $1/usr/include/gnu/

install -d $1/usr/lib
ln -svf ../lib32/ld-linux.so.2 $1/usr/lib/ld-linux.so.2
fi

