#!/bin/sh -e

mkdir build
cd build

../configure --prefix=/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --enable-gprofng=no \
             --disable-werror    \
             --enable-new-dtags  \
             --enable-default-hash-style=gnu

make
make DESTDIR=$1 install

rm $1/tools/usr/share/info/dir
