#!/bin/sh -e
VERSION=$(awk '{print $1}' "$(dirname "$0")/version")
export VERSION

if [ "$MULTILIB" = "1" ]; then
    multilib_opt="--enable-multilib"
else
    multilib_opt="--disable-multilib"
fi

mkdir build
cd build

../libstdc++-v3/configure           \
    --host=$LFS_TGT                 \
    --build=$(../config.guess)      \
    --prefix=/usr                   \
    $multilib_opt                   \
    --disable-nls                   \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/$VERSION

make
make DESTDIR=$1 install

rm -fv $1/usr/lib/lib{stdc++{,exp,fs},supc++}.la
